export const desks = [
  {
    deskId: "1",
    deskName: "100",
    deskTyp: "Standard",
    roomId: " ",
    roomName: "100.1",
    floorId: "",
    floorName: "EG",
    buildingId: "",
    buildingName: "Headquarter",
    location: "Example street 123, 12345 Berlin",
  },
  {
    deskId: "2",
    deskName: "105",
    deskTyp: "Standard",
    roomId: "",
    roomName: "100.1",
    floorId: "",
    floorName: "EG",
    buildingId: "",
    buildingName: "Headquarter",
    location: "Example street 123, 12345 Berlin",
  },
  {
    deskId: "3",
    deskName: "106",
    deskTyp: "Height Adjustable",
    roomId: "",
    roomName: "100.1",
    floorId: "",
    floorName: "EG",
    buildingId: "",
    buildingName: "Headquarter",
    location: "Example street 123, 12345 Berlin",
  },
  {
    deskId: "4",
    deskName: "102",
    deskTyp: "Standard",
    roomId: "",
    roomName: "100.1",
    floorId: "",
    floorName: "1",
    buildingId: "",
    buildingName: "Headquarter",
    location: "Example street 123, 12345 Berlin",
  },
  {
    deskId: "5",
    deskName: "B",
    deskTyp: "Standard",
    roomId: "",
    roomName: "R 20.245",
    floorId: "",
    floorName: "EG",
    buildingId: "",
    buildingName: "Innovation Center",
    location: "Sesamstreet 42, 85757 Karlsfeld",
  },
  {
    deskId: "6",
    deskName: "C",
    deskTyp: "Height-Adjustable",
    roomId: "",
    roomName: "R 20.245",
    floorId: "",
    floorName: "EG",
    buildingId: "",
    buildingName: "Innovation Center",
    location: "Sesamstreet 42, 85757 Karlsfeld",
  },
];
