export const desks = [
    {
        deskId: "1",
        deskName: "100",
        deskType: "Standard",
        room: "100.1",
        floor: "EG",
        building: "Headquarter",
        location: "Example street 123, 12345 Berlin",
    },
    {
        deskId: "2",
        deskName: "105",
        deskType: "Standard",
        room: "100.1",
        floor: "EG",
        building: "Headquarter",
        location: "Example street 123, 12345 Berlin",
    },
    {
        deskId: "3",
        deskName: "106",
        deskType: "Height Adjustable",
        room: "100.1",
        floor: "EG",
        building: "Headquarter",
        location: "Example street 123, 12345 Berlin",
    },
    {
        deskId: "4",
        deskName: "102",
        deskType: "Standard",
        room: "100.1",
        floor: "1",
        building: "Headquarter",
        location: "Example street 123, 12345 Berlin",
    },
    {
        deskId: "5",
        deskName: "B",
        deskType: "Standard",
        room: "R 20.245",
        floor: "EG",
        building: "Innovation Center",
        location: "Sesamstreet 42, 85757 Karlsfeld",
    },
    {
        deskId: "6",
        deskName: "C",
        deskType: "Height-Adjustable",
        room: "R 20.245",
        floor: "EG",
        building: "Innovation Center",
        location: "Sesamstreet 42, 85757 Karlsfeld",
    },
];