export const users = [
    {
        userId: "1",
        firstName: "Donald",
        lastName: "Duck",
        email: "donald@duck.com",
        company: "Dagobert AG",
        isAdmin: false,
        isApproved: true,
    },
    {
        userId: "2",
        firstName: "Dagobert",
        lastName: "Duck",
        email: "dagobert@duck.com",
        company: "Dagobert AG",
        isAdmin: true,
        isApproved: true,
    },
    {
        userId: "3",
        firstName: "Dussel",
        lastName: "Duck",
        email: "dussel@duck.com",
        company: "Dagobert AG",
        isAdmin: false,
        isApproved: false,
    },
    {
        userId: "4",
        firstName: "Daisy",
        lastName: "Duck",
        email: "Daisy@duck.com",
        company: "Dagobert AG",
        isAdmin: true,
        isApproved: true,
    },
    {
        userId: "5",
        firstName: "Gustav",
        lastName: "Gans",
        email: "gustav@gans.com",
        company: "Dagobert AG",
        isAdmin: true,
        isApproved: true,
    },
    {
        userId: "6",
        firstName: "Dorette",
        lastName: "Duck",
        email: "dorette@duck.com",
        company: "Dagobert AG",
        isAdmin: false,
        isApproved: true,
    },
    {
        userId: "7",
        firstName: "Bert",
        lastName: "?",
        email: "bert@sesam.com",
        company: "Dagobert AG",
        isAdmin: false,
        isApproved: false,
    },
    {
        userId: "8",
        firstName: "Ernie",
        lastName: "?",
        email: "ernie@sesam.com",
        company: "Dagobert AG",
        isAdmin: false,
        isApproved: false,
    },
    {
        userId: "9",
        firstName: "Asterix",
        lastName: "?",
        email: "asterix@galien.com",
        company: "Dagobert AG",
        isAdmin: false,
        isApproved: false,
    },
    {
        userId: "10",
        firstName: "Obelix",
        lastName: "?",
        email: "obelix@galien.com",
        company: "Dagobert AG",
        isAdmin: false,
        isApproved: false,
    },

]