services:
  frontend:
    user: "${USER_ID}:${GROUP_ID}" # prevent root files in host system
    build:
      context: ./deskstar-frontend
    ports:
      - 80:3000
    volumes:
      - ./deskstar-frontend:/app/code
      # prevent mounting node_modules of host system into container
      - exclude:/app/code/node_modules 
    command: bash -c "rm -rf /app/code/node_modules/* && yarn run dev" # clean exclude volume on each startup
volumes:
  exclude:
