services:
  frontend:
    user: "${USER_ID}:${GROUP_ID}" # prevent root files in host system
    build:
      context: ./deskstar-frontend
    ports:
      - 80:3000
    volumes:
      - ./deskstar-frontend:/app/code
      # prevent mounting node_modules of host system into container
      - exclude:/app/code/node_modules 
    command: bash -c "rm -rf /app/code/node_modules/* && yarn run dev" # clean exclude volume on each startup
  backend:
    #TODO: import source code via bind mount during runtime
    #TODO: exclude build files of container
    #TODO: clear volumes on each startup
    #TODO: add hot reload
    build: 
      context: ./deskstar-backend
    ports:
      - 3001:80
  postgres:
    build: 
      context: ./deskstar-db
    user: "postgres"
    environment:
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRES_PASSWORD
    volumes:
      - ./deskstar-db/init:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    # reset postgres on each startup
    command: bash -c "rm -rfd /var/lib/postgresql/data/* && docker-entrypoint.sh postgres"
volumes:
  exclude:
