services:
  frontend:
    container_name: deskstar_frontend
    build:
      context: ./deskstar-frontend
      args:
        - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
    ports:
      - ${FRONTEND_EXTERN_PORT:-3000}:3000
    environment:
      - NEXT_PUBLIC_BACKEND_URL
      - NEXTAUTH_SECRET
      - NEXTAUTH_URL
    networks:
      - external
      - internal
  backend:
    container_name: deskstar_backend
    depends_on:
      - "postgres"
    build:
      context: ./deskstar-backend/Deskstar
    ports:
      - ${BACKEND_EXTERN_PORT:-3001}:80
    environment:
      - ASPNETCORE_ENVIRONMENT
      - DB__HOST
      - DB__DATABASE
      - DB__USERNAME
      - DB__PASSWORD
      # defined in .env.local (will no be pushed to git)
      - EMAIL__HOST
      - EMAIL__PORT
      - EMAIL__ADDRESS
      - EMAIL__PSW
    networks:
      - internal
  dbpreparation:
    container_name: deskstar_db_prep
    build:
      context: ./deskstar-backend/Deskstar
      dockerfile: Dockerfile_dev
    depends_on:
      - "postgres"
    environment:
      # - ASPNETCORE_ENVIRONMENT
      - DB__HOST
      - DB__DATABASE
      - DB__USERNAME
      - DB__PASSWORD
      # defined in .env.local (will no be pushed to git)
      - EMAIL__HOST
      - EMAIL__PORT
      - EMAIL__ADDRESS
      - EMAIL__PSW
    networks:
      - internal
    command: dotnet ef database update
  postgres:
    container_name: deskstar_postgres
    image: postgres
    user: "postgres"
    environment:
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRES_PASSWORD
    ports:
      - 5433:5432
    networks:
      - internal
volumes:
  exclude:
networks:
  internal:
  external:
