name: Playwright Tests
on:
  push:
    branches: ["develop", "main"]
  pull_request:
    branches: ["develop", "main"]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: postgres
        ports: ["5432:5432"]

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./src/deskstar-backend/Deskstar

      - name: Build
        run: dotnet build --no-restore
        working-directory: ./src/deskstar-backend/Deskstar

      - name: Install dotnet ef
        run: dotnet tool install --global dotnet-ef

      - name: Run database migration
        run: dotnet ef database update
        working-directory: ./src/deskstar-backend/Deskstar
        env:
          DB__HOST: db
          DB__DATABASE: postgres
          DB__USERNAME: postgres
          DB__PASSWORD: postgres
          EMAIL__HOST: example.com
          EMAIL__PORT: 467
          EMAIL__ADDRESS: test@example.com
          EMAIL__PSW: test

      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        working-directory: ./src/deskstar-frontend
        run: yarn

      - name: Install Playwright Browsers
        working-directory: ./src/deskstar-frontend
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        working-directory: ./src/deskstar-frontend
        run: yarn playwright test

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: ./src/deskstar-frontend/playwright-report/
          retention-days: 30
